@HOST = http://localhost:8080

// ===> API LOGIN <===
POST {{HOST}}/login 
content-type: application/json

{
    "username": "test",
    "password": "test"
}

### 

// ===> API REGISTER <===
POST {{HOST}}/register 
content-type: application/json

  {
    "username": "test",
    "password": "test",
    "nama": "User Test",
    "alamat": "jl.localhost no 127.0.0.1",
    "no_hp": "081791833333",
    "role": "siswa"
   }

### 

// ===> API LOGOUT <===
POST   {{HOST}}/logout 
content-type: application/json

###

// ===> GET ALL TEACHERS <===
GET {{HOST}}/v1/teachers
content-type: application/json

###

// ===> GET ALL TEACHER WITH PARAMS <===
// page => for set current page
// per_page => to set the amount of data you want to display every single
GET {{HOST}}/v1/teachers?page=1&per_page=1
content-type: application/json
